-- 테이블 삭제
DROP TABLE CUSTOMER;
DROP TABLE BANK;

-- 테이블 생성
CREATE TABLE BANK (
    BANK_CODE VARCHAR2(20 BYTE) NOT NULL,
    BANK_NAME VARCHAR2(30 BYTE) NULL
);


-- 테이블 생성
CREATE TABLE CUSTOMER (
    NO          NUMBER            NOT NULL,
    NAME        VARCHAR2(30 BYTE) NOT NULL,
    PHONE       VARCHAR2(30 BYTE) NULL UNIQUE,
    AGE         NUMBER(2)         NULL,
    BANK_CODE   VARCHAR2(20 BYTE) 
);

-- 기본키 추가
ALTER TABLE BANK
    ADD CONSTRAINT PK_BANK PRIMARY KEY (BANK_CODE);
    
ALTER TABLE CUSTOMER 
    ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (NO);

-- 외래키 추가
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMER_BANK FOREIGN KEY (BANK_CODE)
        REFERENCES BANK (BANK_CODE)
            ON DELETE CASCADE;