DROP TABLE SCHEDULE;
DROP TABLE PLAYER;
DROP TABLE EVENT;
DROP TABLE NATION;


CREATE TABLE NATION(
    N_CODE          NUMBER(3)         NOT NULL,
    N_NAME          VARCHAR2(30 BYTE) NOT NULL,
    N_PARTI_PERSON  NUMBER            NULL,
    N_PARTI_EVENT   NUMBER            NULL,
    N_PREV_RANK     NUMBER            NULL,
    N_CURR_RANK     NUMBER            NULL,
    CONSTRAINT PK_N_CODE PRIMARY KEY (N_CODE)
);

CREATE TABLE EVENT(
    E_CODE          NUMBER             NOT NULL,
    E_NAME          VARCHAR2(30 BYTE)  NOT NULL,
    E_FIRST_YEAR    NUMBER(4)          NULL,
    E_INFO          VARCHAR2(100 BYTE) NULL,
    CONSTRAINT PK_E_CODE PRIMARY KEY (E_CODE)
);

CREATE TABLE PLAYER(
    P_CODE      NUMBER(3)            NOT NULL,
    P_NAME      VARCHAR2(30 BYTE)    NOT NULL,
    N_CODE      NUMBER(3)            NOT NULL,
    E_CODE      NUMBER               NOT NULL,
    P_RANK      NUMBER               NULL,
    P_AGE       NUMBER               NULL,
    CONSTRAINT PK_P_CODE PRIMARY KEY (P_CODE),
    CONSTRAINT FK_PLAYER_NATION FOREIGN KEY (N_CODE) REFERENCES NATION(N_CODE)
    ON DELETE CASCADE,
    CONSTRAINT FK_PLAYER_EVENT FOREIGN KEY (E_CODE) REFERENCES EVENT(E_CODE)
    ON DELETE CASCADE
);

CREATE TABLE SCHEDULE(
    S_NO            NUMBER(3)          NOT NULL,
    N_CODE          NUMBER(3)          NULL,
    E_CODE          NUMBER             NULL,
    S_START_DATE    DATE               NULL,
    S_INFO          VARCHAR2(100 BYTE) NULL,
    CONSTRAINT PK_S_NO PRIMARY KEY (S_NO),
    CONSTRAINT FK_SCHEDULE_NATION FOREIGN KEY (N_CODE) REFERENCES NATION(N_CODE)
    ON DELETE SET NULL,
    CONSTRAINT FK_SCHEDULE_EVENT FOREIGN KEY (E_CODE) REFERENCES EVENT(E_CODE)
    ON DELETE SET NULL
);
