-- 함수 확인용 기초데이터
DROP TABLE SAMPLE;
CREATE TABLE SAMPLE(
    NAME VARCHAR2(20 BYTE),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MATH NUMBER(3)
);

INSERT INTO SAMPLE (NAME, KOR, ENG, MATH) VALUES(NULL, 100,100,100);
INSERT INTO SAMPLE (NAME, KOR, ENG, MATH) VALUES('영숙', NULL, 100, 100);
INSERT INTO SAMPLE (NAME, KOR, ENG, MATH) VALUES('정수', 100, NULL, 100);
INSERT INTO SAMPLE (NAME, KOR, ENG, MATH) VALUES('지영', 100, 100, NULL);
COMMIT;


-- NULL 값의 연산에서 사용되면 결과가 NULL이다.
SELECT 1 + NULL FROM DUAL;

-- NULL 처리 함수

-- 1. NVL 함수
--    NVL (칼럼, 칼럼 값이 NULL 일 때 대신 사용할 값)

-- NAME이 없으면 '아무개', KOR,ENG,MATH가 없으면 0으로 조회
SELECT
    NVL(NAME, '아무개') AS STU_NAME
   ,NVL(KOR,0)
   ,NVL(ENG,0)
   ,NVL(MATH,0)
  FROM
    SAMPLE
  WHERE
    STU_NAME != '아무개'
  ORDER BY
    STU_NAME ASC;


