DROP TABLESPACE MY_SPACE;

CREATE TABLESPACE MY_SPACE
    DATAFILE 'C:/oraclexe/my_space.dbf'
    SIZE 10M;


DROP TABLE MEMBER_LOG;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
     MEMBER_NO   NUMBER                   NOT NULL
    ,ID         VARCHAR2(30 BYTE) UNIQUE  NOT NULL
    ,PW         VARCHAR2(30 BYTE)         NOT NULL
    ,NAME       VARCHAR2(30 BYTE)         NULL
    ,PHONE      VARCHAR2(15 BYTE)         NULL
);   

CREATE TABLE MEMBER_LOG (
     LOG_NO      NUMBER             NOT NULL
    ,MEMBER_NO   NUMBER             NOT NULL
    ,LOGIN       DATE               NULL
);

ALTER TABLE MEMBER
    ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO);
    
ALTER TABLE MEMBER_LOG
    ADD CONSTRAINT PK_MEMBER_LOG PRIMARY KEY (LOG_NO);
    
ALTER TABLE MEMBER_LOG
    ADD CONSTRAINT FK_MEMBER_LOG_MEMBER FOREIGN KEY (MEMBER_NO) 
    REFERENCES MEMBER(MEMBER_NO);
    
