DROP TABLE MEMBER;

-- 블로그
CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER NOT NULL,
    ID VARCHAR2(30 BYTE) NOT NULL UNIQUE,
    NAME VARCHAR2(30 BYTE),
    GENDER VARCHAR2(1 BYTE),
    ADDRESS VARCHAR2(30 BYTE)
);

-- 블로그 기본키
ALTER TABLE MEMBER
    ADD CONSTRAINT PK_MEMBER
        PRIMARY KEY(MEMBER_NO);

-- 시퀀스
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;

COMMIT;
